export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// Categories
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_PENDING = "GET_CATEGORY_PENDING";

// Products
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_PENDING = "GET_PRODUCTS_PENDING";

// Offer
export const GIVE_PRODUCT_OFFER_SUCCESS = "GIVE_PRODUCT_OFFER_SUCCESS";
export const GIVE_PRODUCT_OFFER_PENDING = "GIVE_PRODUCT_OFFER_PENDING";

// Received Offers
export const RECEIVED_OFFER_SUCCESS = "RECEIVED_OFFER_SUCCESS";
export const RECEIVED_OFFER_PENDING = "RECEIVED_OFFER_PENDING";

// Given Offers
export const GIVEN_OFFER_SUCCESS = "GIVEN_OFFER_SUCCESS";
export const GIVEN_OFFER_PENDING = "GIVEN_OFFER_PENDING";

// Purchase Item
export const PURCHASE_ITEM_SUCCESS = "PURCHASE_ITEM_SUCCESS";
export const PURCHASE_ITEM_PENDING = "PURCHASE_ITEM_PENDING";

// Status
export const ITEM_STATUS_SUCCESS = "ITEM_STATUS_SUCCESS";
export const ITEM_STATUS_PENDING = "ITEM_STATUS_PENDING";

// Brands
export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS";
export const GET_BRANDS_PENDING = "GET_BRANDS_PENDING";

// Colors
export const GET_COLORS_SUCCESS = "GET_COLORS_SUCCESS";
export const GET_COLORS_PENDING = "GET_COLORS_PENDING";

// New Product Upload
export const ADD_NEW_PRODUCT_PENDING = "ADD_NEW_PRODUCT_PENDING";
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";
export const ADD_NEW_PRODUCT_FAIL = "ADD_NEW_PRODUCT_FAIL";

// Accept Offer
export const ACCEPT_OFFER_PENDING = "ACCEPT_OFFER_PENDING";
export const ACCEPT_OFFER_SUCCESS = "ACCEPT_OFFER_SUCCESS";
export const ACCEPT_OFFER_FAIL = "ACCEPT_OFFER_FAIL";

// Reject Offer
export const REJECT_OFFER_PENDING = "REJECT_OFFER_PENDING";
export const REJECT_OFFER_SUCCESS = "REJECT_OFFER_SUCCESS";
export const REJECT_OFFER_FAIL = "REJECT_OFFER_FAIL";
